// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG-PQ80gyM3hcHPdPkQC1L6lEIFF3sZtM',
    appId: '1:625002506307:web:67fcee505bc2807f250cf6',
    messagingSenderId: '625002506307',
    projectId: 'chatapp-848ff',
    authDomain: 'chatapp-848ff.firebaseapp.com',
    storageBucket: 'chatapp-848ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwomO2R7dCIw0jLSI8oadO7MwVBkJ4FhY',
    appId: '1:625002506307:android:e47f09b75555e7b4250cf6',
    messagingSenderId: '625002506307',
    projectId: 'chatapp-848ff',
    storageBucket: 'chatapp-848ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaZNBOTJZMqtcT7iT3V4gupEEAx-FyR7c',
    appId: '1:625002506307:ios:66eaae940592e8b8250cf6',
    messagingSenderId: '625002506307',
    projectId: 'chatapp-848ff',
    storageBucket: 'chatapp-848ff.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
